apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
  labels:
    app: traffic-generator
spec:
  containers:
  - name: traffic-generator
    image: lmacademy/traffic-generator:1.0.0
    args: 
      - '10.96.178.143/api' # ClusterIP Service IP 
    # - 'color-api-clusterip/api' can use namespace and service name instead of IP
      - '0.5' # 0.5 seconds between requests
